package meupaint;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author filipe
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());
    
    private Forma forma;
    private int ladosPoligono = 3;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelDesenho = new meupaint.PainelDesenho();
        painelForms = new javax.swing.JPanel();
        botaoLinha = new javax.swing.JToggleButton();
        botaoRetangulo = new javax.swing.JToggleButton();
        botaoElipse = new javax.swing.JToggleButton();
        painelContorno = new javax.swing.JPanel();
        painelPreenchimento = new javax.swing.JPanel();
        botaoPoligono = new javax.swing.JToggleButton();
        botaoBorracha = new javax.swing.JToggleButton();
        botaoLimpar = new javax.swing.JButton();
        botaoCaneta = new javax.swing.JToggleButton();
        Desfazer = new javax.swing.JButton();
        Refazer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MeuPaint");

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        painelForms.setBorder(javax.swing.BorderFactory.createTitledBorder("Ferramentas"));

        buttonGroup.add(botaoLinha);
        botaoLinha.setSelected(true);
        botaoLinha.setText("Linha");
        botaoLinha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup.add(botaoRetangulo);
        botaoRetangulo.setText("Retângulo");
        botaoRetangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup.add(botaoElipse);
        botaoElipse.setText("Elipse");
        botaoElipse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painelContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelContorno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelContorno.setToolTipText("Cor do Contorno");
        painelContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelContornoLayout = new javax.swing.GroupLayout(painelContorno);
        painelContorno.setLayout(painelContornoLayout);
        painelContornoLayout.setHorizontalGroup(
            painelContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelContornoLayout.setVerticalGroup(
            painelContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        painelPreenchimento.setBackground(new java.awt.Color(255, 255, 255));
        painelPreenchimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelPreenchimento.setToolTipText("Cor do Preenchimento");
        painelPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelPreenchimentoLayout = new javax.swing.GroupLayout(painelPreenchimento);
        painelPreenchimento.setLayout(painelPreenchimentoLayout);
        painelPreenchimentoLayout.setHorizontalGroup(
            painelPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelPreenchimentoLayout.setVerticalGroup(
            painelPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        buttonGroup.add(botaoPoligono);
        botaoPoligono.setText("Polígonos");
        botaoPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPoligonoActionPerformed(evt);
            }
        });

        buttonGroup.add(botaoBorracha);
        botaoBorracha.setText("Borracha");
        botaoBorracha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        buttonGroup.add(botaoCaneta);
        botaoCaneta.setText("Caneta");
        botaoCaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCanetaActionPerformed(evt);
            }
        });

        Desfazer.setText("Desfazer");
        Desfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesfazerActionPerformed(evt);
            }
        });

        Refazer.setText("Refazer");
        Refazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefazerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFormsLayout = new javax.swing.GroupLayout(painelForms);
        painelForms.setLayout(painelFormsLayout);
        painelFormsLayout.setHorizontalGroup(
            painelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCaneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoBorracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRetangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoElipse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Desfazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(painelPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelFormsLayout.setVerticalGroup(
            painelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(botaoRetangulo)
                .addComponent(botaoElipse)
                .addComponent(painelContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(painelPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoPoligono)
                .addComponent(botaoBorracha)
                .addComponent(botaoLimpar)
                .addComponent(botaoCaneta)
                .addComponent(Desfazer)
                .addComponent(Refazer)
                .addComponent(botaoLinha))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelForms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        if(!botaoBorracha.isSelected()) {
            forma.setX2(evt.getX());
            forma.setY2(evt.getY());
            painelDesenho.addForma(forma);
            painelDesenho.setFormaTemp(null);

            painelDesenho.repaint();    
        }
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private static final int TAMANHO_BORRACHA = 20;
    private static final int TAMANHO_CANETA = 5;
    
    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
       
      
        
        if(botaoLinha.isSelected() ) {
            forma = new Linha();
        } else if(botaoRetangulo.isSelected()) {
            forma = new Retangulo();
        } else if(botaoElipse.isSelected()) {
            forma = new Elipse();
        } else if(botaoPoligono.isSelected()) {
            forma = new Poligono(ladosPoligono);
        } else if(botaoBorracha.isSelected()) {
            forma = new Retangulo();
            forma.setContorno(Color.WHITE);
            forma.setPreenchimento(Color.WHITE);
        } else if(botaoCaneta.isSelected()) {
            forma = new Elipse();
            forma.setContorno(painelContorno.getBackground());
            forma.setPreenchimento(painelContorno.getBackground());
        }
        
        forma.setX1(evt.getX());
        forma.setY1(evt.getY());
        
        if(!botaoBorracha.isSelected() || !botaoCaneta.isSelected()) {
            forma.setContorno(painelContorno.getBackground());
            forma.setPreenchimento(painelPreenchimento.getBackground());
        } else {
            forma.setContorno(painelPreenchimento.getBackground());
            forma.setPreenchimento(painelPreenchimento.getBackground());
            forma.setX2(evt.getX() + TAMANHO_BORRACHA);
            forma.setY2(evt.getY() + TAMANHO_BORRACHA);
            painelDesenho.addForma(forma);
            painelDesenho.repaint();
        }
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        if(botaoBorracha.isSelected()) {
            forma = new Retangulo();
            forma.setPreenchimento(painelPreenchimento.getBackground());
            forma.setContorno(painelPreenchimento.getBackground());
            forma.setX1(evt.getX());
            forma.setY1(evt.getY());
            forma.setX2(evt.getX() + TAMANHO_BORRACHA);
            forma.setY2(evt.getY() + TAMANHO_BORRACHA);
            painelDesenho.addForma(forma);
            painelDesenho.repaint();           
        } else if(botaoCaneta.isSelected()) {
            forma = new Elipse();
            forma.setContorno(painelContorno.getBackground());
            forma.setPreenchimento(painelContorno.getBackground());
            forma.setX1(evt.getX());
            forma.setY1(evt.getY());
            forma.setX2(evt.getX() + TAMANHO_CANETA);
            forma.setY2(evt.getY() + TAMANHO_CANETA);
            painelDesenho.addForma(forma);
            painelDesenho.repaint();
        } else {
            forma.setX2(evt.getX());
            forma.setY2(evt.getY());
            painelDesenho.setFormaTemp(forma);
            painelDesenho.repaint();
        }
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void painelContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelContornoMouseClicked
        Color c = JColorChooser.showDialog(this, "Cor do Contorno", painelContorno.getBackground());
        
        if(c != null) {
            painelContorno.setBackground(c);
        }
    }//GEN-LAST:event_painelContornoMouseClicked

    private void painelPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelPreenchimentoMouseClicked
         Color c = JColorChooser.showDialog(this, "Cor do Preenchimento", painelPreenchimento.getBackground());
        
        if(c != null) {
            painelPreenchimento.setBackground(c);
        }
    }//GEN-LAST:event_painelPreenchimentoMouseClicked

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        painelDesenho.limpar();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCanetaActionPerformed

    private void DesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesfazerActionPerformed
        painelDesenho.desfazer();
    }//GEN-LAST:event_DesfazerActionPerformed

    private void RefazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefazerActionPerformed
         painelDesenho.refazer();
    }//GEN-LAST:event_RefazerActionPerformed

    private void botaoPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPoligonoActionPerformed
            String input = JOptionPane.showInputDialog(this, "Digite a quantidade de lados:",ladosPoligono);

    if(input != null) {
        try {
            int valor = Integer.parseInt(input);
            if(valor >= 3) {
                ladosPoligono = valor;
            } else {
                JOptionPane.showMessageDialog(this, "O polígono deve ter ao menos 3 lados.", "ERRO!", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Digite um número válido.","ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_botaoPoligonoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desfazer;
    private javax.swing.JButton Refazer;
    private javax.swing.JToggleButton botaoBorracha;
    private javax.swing.JToggleButton botaoCaneta;
    private javax.swing.JToggleButton botaoElipse;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JToggleButton botaoLinha;
    private javax.swing.JToggleButton botaoPoligono;
    private javax.swing.JToggleButton botaoRetangulo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel painelContorno;
    private meupaint.PainelDesenho painelDesenho;
    private javax.swing.JPanel painelForms;
    private javax.swing.JPanel painelPreenchimento;
    // End of variables declaration//GEN-END:variables
}
